# Generated by Django 5.2.5 on 2025-08-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_remove_order_is_completed_customer_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
